import { NavGroup } from "@/app/(DashboardLayout)/types/layout/sidebar";
import { uniqueId } from "lodash";

const Menuitems: NavGroup[] = [
  {
    navlabel: true,
    subheader: "Personal",
  },

  {
    id: uniqueId(),
    title: "General",
    icon: "solar:screencast-2-linear",
    href: "/",
  },
  {
    id: uniqueId(),
    title: "Histórico",
    icon: "solar:history-linear",
    href: "/dashboards/historico",
  },
  {
    id: uniqueId(),
    title: "Analytical",
    icon: "solar:box-minimalistic-linear",
    href: "/dashboards/analytical",
  },
  {
    id: uniqueId(),
    title: "Campaign",
    icon: "solar:buildings-2-linear",
    href: "/dashboards/campaign",
  },
  {
    id: uniqueId(),
    title: "Modern",
    icon: "solar:basketball-linear",
    href: "/dashboards/modern",
  },
  {
    id: uniqueId(),
    title: "eCommerce",
    icon: "solar:cart-large-2-linear",
    href: "/dashboards/ecommerce",
  },
  {
    id: uniqueId(),
    title: "Frontend pages",
    icon: "solar:home-angle-linear",
    href: "/frontend-pages/",
    children: [
      {
        id: uniqueId(),
        title: "Homepage",
        icon: "solar:stop-circle-line-duotone",
        href: "/frontend-pages/homepage",
      },
      {
        id: uniqueId(),
        title: "About Us",
        icon: "solar:stop-circle-line-duotone",
        href: "/frontend-pages/about",
      },
      {
        id: uniqueId(),
        title: "Blog",
        icon: "solar:stop-circle-line-duotone",
        href: "/frontend-pages/blog",
      },
      {
        id: uniqueId(),
        title: "Blog Details",
        icon: "solar:stop-circle-line-duotone",
        href: "/frontend-pages/blog/Blog_1",
      },
      {
        id: uniqueId(),
        title: "Contact",
        icon: "solar:stop-circle-line-duotone",
        href: "/frontend-pages/contact",
      },
      {
        id: uniqueId(),
        title: "Portfolio",
        icon: "solar:stop-circle-line-duotone",
        href: "/frontend-pages/portfolio",
      },
      {
        id: uniqueId(),
        title: "Pricing",
        icon: "solar:stop-circle-line-duotone",
        href: "/frontend-pages/pricing",
      },
    ],
  },
  {
    navlabel: true,
    subheader: "Apps",
  },
  {
    id: uniqueId(),
    title: "Contacts",
    icon: "solar:list-check-linear",
    chip: "2",
    chipColor: "secondary",
    href: "/apps/contacts",
  },

  {
    id: uniqueId(),
    title: "Blog",
    icon: "solar:widget-4-linear",
    href: "/apps/blog/",
    children: [
      {
        id: uniqueId(),
        title: "Posts",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/blog/post",
      },
      {
        id: uniqueId(),
        title: "Detail",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/blog/detail/streaming-video-way-before-it-was-cool-go-dark-tomorrow",
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Ecommerce",
    icon: "solar:cart-2-linear",
    href: "/apps/ecommerce/",
    children: [
      {
        id: uniqueId(),
        title: "Shop",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/ecommerce/shop",
      },
      {
        id: uniqueId(),
        title: "Detail",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/ecommerce/detail/1",
      },
      {
        id: uniqueId(),
        title: "List",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/ecommerce/list",
      },
      {
        id: uniqueId(),
        title: "Checkout",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/ecommerce/checkout",
      },
      {
        id: uniqueId(),
        title: "Add Product",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/ecommerce/add-product",
      },
      {
        id: uniqueId(),
        title: "Edit Product",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/ecommerce/edit-product",
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Chats",
    icon: "solar:chat-line-linear",
    href: "/apps/chats",
  },
  {
    id: uniqueId(),
    title: "Users",
    icon: "solar:user-circle-linear",
    href: "/apps/user-profile/profile",
    children: [
      {
        id: uniqueId(),
        title: "Profile",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/user-profile/profile",
      },
      {
        id: uniqueId(),
        title: "Followers",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/user-profile/followers",
      },
      {
        id: uniqueId(),
        title: "Friends",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/user-profile/friends",
      },
      {
        id: uniqueId(),
        title: "Gallery",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/user-profile/gallery",
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Notes",
    icon: "solar:palette-linear",
    href: "/apps/notes",
  },
  {
    id: uniqueId(),
    title: "Calendar",
    icon: "solar:calendar-linear",
    href: "/apps/calendar",
  },
  {
    id: uniqueId(),
    title: "Email",
    icon: "solar:letter-unread-linear",
    href: "/apps/email",
  },
  {
    id: uniqueId(),
    title: "Tickets",
    icon: "solar:ticket-sale-linear",
    href: "/apps/tickets",
  },
  {
    id: uniqueId(),
    title: "Kanban",
    icon: "solar:notes-linear",
    href: "/apps/kanban",
  },

  {
    id: uniqueId(),
    title: "Invoice",
    icon: "solar:bill-list-linear",
    href: "/apps/invoice/list",
    children: [
      {
        id: uniqueId(),
        title: "List",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/invoice/list",
      },
      {
        id: uniqueId(),
        title: "Details",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/invoice/detail/PineappleInc",
      },
      {
        id: uniqueId(),
        title: "Create",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/invoice/create",
      },
      {
        id: uniqueId(),
        title: "Edit",
        icon: "solar:stop-circle-line-duotone",
        href: "/apps/invoice/edit/PineappleInc",
      },
    ],
  },
  {
    navlabel: true,
    subheader: "Pages",
  },

  {
    id: uniqueId(),
    title: "Roll Base Access",
    icon: "solar:accessibility-linear",
    href: "/theme-pages/casl",
  },
  {
    id: uniqueId(),
    title: "Pricing",
    icon: "solar:dollar-minimalistic-linear",
    href: "/theme-pages/pricing",
  },
  {
    id: uniqueId(),
    title: "Account Setting",
    icon: "solar:settings-linear",
    href: "/theme-pages/account-settings",
  },
  {
    id: uniqueId(),
    title: "FAQ",
    icon: "solar:question-circle-linear",
    href: "/theme-pages/faq",
  },
  {
    id: uniqueId(),
    title: "Landingpage",
    icon: "solar:align-vertical-spacing-linear",
    href: "/landingpage",
  },

  {
    navlabel: true,
    subheader: "Forms",
  },
  {
    id: uniqueId(),
    title: "Form Elements",
    icon: "solar:notification-unread-lines-linear",
    href: "/forms/form-elements/autocomplete",
    children: [
      {
        id: uniqueId(),
        title: "Autocomplete",
        icon: "solar:stop-circle-line-duotone",
        href: "/forms/form-elements/autocomplete",
      },
      {
        id: uniqueId(),
        title: "Button",
        icon: "solar:stop-circle-line-duotone",
        href: "/forms/form-elements/button",
      },
      {
        id: uniqueId(),
        title: "Checkbox",
        icon: "solar:stop-circle-line-duotone",
        href: "/forms/form-elements/checkbox",
      },
      {
        id: uniqueId(),
        title: "Radio",
        icon: "solar:stop-circle-line-duotone",
        href: "/forms/form-elements/radio",
      },
      {
        id: uniqueId(),
        title: "Date Time",
        icon: "solar:stop-circle-line-duotone",
        href: "/forms/form-elements/date-time",
      },
      {
        id: uniqueId(),
        title: "Slider",
        icon: "solar:stop-circle-line-duotone",
        href: "/forms/form-elements/slider",
      },
      {
        id: uniqueId(),
        title: "Switch",
        icon: "solar:stop-circle-line-duotone",
        href: "/forms/form-elements/switch",
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Form Layout",
    icon: "solar:file-text-linear",
    href: "/forms/form-layout",
  },
  {
    id: uniqueId(),
    title: "Form Horizontal",
    icon: "solar:file-check-linear",
    href: "/forms/form-horizontal",
  },
  {
    id: uniqueId(),
    title: "Form Vertical",
    icon: "solar:file-favourite-linear",
    href: "/forms/form-vertical",
  },
  {
    id: uniqueId(),
    title: "Form Custom",
    icon: "solar:file-smile-linear",
    href: "/forms/form-custom",
  },
  {
    id: uniqueId(),
    title: "Form Wizard",
    icon: "solar:download-twice-square-linear",
    href: "/forms/form-wizard",
  },
  {
    id: uniqueId(),
    title: "Form Validation",
    icon: "solar:shield-warning-linear",
    href: "/forms/form-validation",
  },
  {
    id: uniqueId(),
    title: "Tiptap Editor",
    icon: "solar:stop-circle-line-duotone",
    href: "/forms/form-tiptap",
  },
  {
    navlabel: true,
    subheader: "Widgets",
  },

  {
    id: uniqueId(),
    title: "Cards",
    icon: "solar:card-linear",
    href: "/widgets/cards",
  },
  {
    id: uniqueId(),
    title: "Banners",
    icon: "solar:widget-6-linear",
    href: "/widgets/banners",
  },
  {
    id: uniqueId(),
    title: "Charts",
    icon: "solar:chart-linear",
    href: "/widgets/charts",
  },
  {
    navlabel: true,
    subheader: "Tables",
  },
  {
    id: uniqueId(),
    title: "Basic",
    icon: "solar:window-frame-linear",
    href: "/tables/basic",
  },
  {
    id: uniqueId(),
    title: "Collapsible",
    icon: "solar:code-scan-linear",
    href: "/tables/collapsible",
  },
  {
    id: uniqueId(),
    title: "Enhanced",
    icon: "solar:command-linear",
    href: "/tables/enhanced",
  },
  {
    id: uniqueId(),
    title: "Fixed Header",
    icon: "solar:feed-linear",
    href: "/tables/fixed-header",
  },
  {
    id: uniqueId(),
    title: "Pagination",
    icon: "solar:filters-linear",
    href: "/tables/pagination",
  },
  {
    id: uniqueId(),
    title: "Search",
    icon: "solar:card-search-linear",
    href: "/tables/search",
  },
  {
    id: uniqueId(),
    title: "React Table",
    icon: "solar:sidebar-code-linear",
    href: "/react-tables/basic",
    children: [
      {
        id: uniqueId(),
        title: "Basic",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/basic",
      },
      {
        id: uniqueId(),
        title: "Dense",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/dense",
      },
      {
        id: uniqueId(),
        title: "Filter",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/filter",
      },
      {
        id: uniqueId(),
        title: "Row Selection",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/row-selection",
      },
      {
        id: uniqueId(),
        title: "Pagination",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/pagination",
      },
      {
        id: uniqueId(),
        title: "Sorting",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/sorting",
      },
      {
        id: uniqueId(),
        title: "Column Visibility",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/column-visiblity",
      },
      {
        id: uniqueId(),
        title: "Drag n Drop",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/drag-n-drop",
      },
      {
        id: uniqueId(),
        title: "Editable",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/editable",
      },
      {
        id: uniqueId(),
        title: "Empty",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/empty",
      },
      {
        id: uniqueId(),
        title: "Expand",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/expanding",
      },
      {
        id: uniqueId(),
        title: "Sticky",
        icon: "solar:stop-circle-line-duotone",
        href: "/react-tables/sticky",
      },
    ],
  },
  {
    navlabel: true,
    subheader: "UI",
  },
  {
    id: uniqueId(),
    title: "Ui Components",
    icon: "solar:widget-linear",
    href: "/ui-components/alert",
    children: [
      {
        id: uniqueId(),
        title: "Alert",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/alert",
      },
      {
        id: uniqueId(),
        title: "Accordion",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/accordion",
      },
      {
        id: uniqueId(),
        title: "Avatar",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/avatar",
      },
      {
        id: uniqueId(),
        title: "Chip",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/chip",
      },
      {
        id: uniqueId(),
        title: "Dialog",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/dialog",
      },
      {
        id: uniqueId(),
        title: "List",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/list",
      },
      {
        id: uniqueId(),
        title: "Popover",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/popover",
      },
      {
        id: uniqueId(),
        title: "Rating",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/rating",
      },
      {
        id: uniqueId(),
        title: "Tabs",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/tabs",
      },
      {
        id: uniqueId(),
        title: "Tooltip",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/tooltip",
      },
      {
        id: uniqueId(),
        title: "Transfer List",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/transfer-list",
      },
      {
        id: uniqueId(),
        title: "Typography",
        icon: "solar:stop-circle-line-duotone",
        href: "/ui-components/typography",
      },
    ],
  },

  {
    navlabel: true,
    subheader: "Charts",
  },
  {
    id: uniqueId(),
    title: "Line",
    icon: "solar:chart-linear",
    href: "/charts/line",
  },
  {
    id: uniqueId(),
    title: "Gradient",
    icon: "solar:chart-square-linear",
    href: "/charts/gradient",
  },
  {
    id: uniqueId(),
    title: "Area",
    icon: "solar:colour-tuneing-linear",
    href: "/charts/area",
  },
  {
    id: uniqueId(),
    title: "Candlestick",
    icon: "solar:align-left-outline",
    href: "/charts/candlestick",
  },
  {
    id: uniqueId(),
    title: "Column",
    icon: "solar:chart-2-linear",
    href: "/charts/column",
  },
  {
    id: uniqueId(),
    title: "Doughtnut & Pie",
    icon: "solar:pie-chart-3-linear",
    href: "/charts/doughnut",
  },
  {
    id: uniqueId(),
    title: "RadialBar & Radar",
    icon: "solar:pie-chart-linear",
    href: "/charts/radialbar",
  },
  {
    navlabel: true,
    subheader: "Icons",
  },
  {
    id: uniqueId(),
    title: "Tabler",
    icon: "solar:face-scan-circle-linear",
    href: "/icons",
  },
  {
    navlabel: true,
    subheader: "Mui Charts",
  },
  {
    id: uniqueId(),
    title: "Bar Charts",
    icon: "solar:chart-square-linear",
    href: "/muicharts/barcharts",
  },
  {
    id: uniqueId(),
    title: "Line Charts",
    icon: "solar:chart-linear",
    href: "/muicharts/linecharts/line",
    children: [
      {
        id: uniqueId(),
        title: "Lines",
        icon: "solar:stop-circle-line-duotone",
        href: "/muicharts/linecharts/line",
      },
      {
        id: uniqueId(),
        title: "Area",
        icon: "solar:stop-circle-line-duotone",
        href: "/muicharts/linecharts/area",
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Pie Charts",
    icon: "solar:pie-chart-2-linear",
    href: "/muicharts/piecharts",
  },
  {
    id: uniqueId(),
    title: "Scatter Charts",
    icon: "solar:align-bottom-linear",
    href: "/muicharts/scattercharts",
  },
  {
    id: uniqueId(),
    title: "Sparkline Charts",
    icon: "solar:chart-2-line-duotone",
    href: "/muicharts/sparklinecharts",
  },
  {
    id: uniqueId(),
    title: "Gauge Charts",
    icon: "solar:pie-chart-outline",
    href: "/muicharts/gaugecharts",
  },

  {
    navlabel: true,
    subheader: "Mui Trees",
  },
  {
    id: uniqueId(),
    title: "TreeView",
    icon: "solar:benzene-ring-broken",
    href: "/mui-trees/simpletree/simpletree-items",
    children: [
      {
        id: uniqueId(),
        title: "Items",
        icon: "solar:stop-circle-line-duotone",
        href: "/mui-trees/simpletree/simpletree-items",
      },
      {
        id: uniqueId(),
        title: "Selection",
        icon: "solar:stop-circle-line-duotone",
        href: "/mui-trees/simpletree/simpletree-selection",
      },
      {
        id: uniqueId(),
        title: "Expansion",
        icon: "solar:stop-circle-line-duotone",
        href: "/mui-trees/simpletree/simpletree-expansion",
      },
      {
        id: uniqueId(),
        title: "Customization",
        icon: "solar:stop-circle-line-duotone",
        href: "/mui-trees/simpletree/simpletree-customization",
      },
      {
        id: uniqueId(),
        title: "Focus",
        icon: "solar:stop-circle-line-duotone",
        href: "/mui-trees/simpletree/simpletree-focus",
      },
    ],
  },
  {
    navlabel: true,
    subheader: "Auth",
  },

  {
    id: uniqueId(),
    title: "Login",
    icon: "solar:lock-keyhole-minimalistic-linear",
    href: "/auth/auth1/login",
    children: [
      {
        id: uniqueId(),
        title: "Side Login",
        icon: "solar:stop-circle-line-duotone",
        href: "/auth/auth1/login",
      },
      {
        id: uniqueId(),
        title: "Boxed Login",
        icon: "solar:stop-circle-line-duotone",
        href: "/auth/auth2/login",
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Register",
    icon: "solar:user-plus-rounded-linear",
    href: "/auth/auth1/register",
    children: [
      {
        id: uniqueId(),
        title: "Side Register",
        icon: "solar:stop-circle-line-duotone",
        href: "/auth/auth1/register",
      },
      {
        id: uniqueId(),
        title: "Boxed Register",
        icon: "solar:stop-circle-line-duotone",
        href: "/auth/auth2/register",
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Forgot Password",
    icon: "solar:password-minimalistic-input-linear",
    href: "/auth/auth1/forgot-password",
    children: [
      {
        id: uniqueId(),
        title: "Side Forgot Password",
        icon: "solar:stop-circle-line-duotone",
        href: "/auth/auth1/forgot-password",
      },
      {
        id: uniqueId(),
        title: "Boxed Forgot Password",
        icon: "solar:stop-circle-line-duotone",
        href: "/auth/auth2/forgot-password",
      },
    ],
  },

  {
    id: uniqueId(),
    title: "Two Steps",
    icon: "solar:compass-big-linear",
    href: "/auth/auth1/two-steps",
    children: [
      {
        id: uniqueId(),
        title: "Side Two Steps",
        icon: "solar:stop-circle-line-duotone",
        href: "/auth/auth1/two-steps",
      },
      {
        id: uniqueId(),
        title: "Boxed Two Steps",
        icon: "solar:stop-circle-line-duotone",
        href: "/auth/auth2/two-steps",
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Error",
    icon: "solar:shield-warning-linear",
    href: "/auth/error",
  },
  {
    id: uniqueId(),
    title: "Maintenance",
    icon: "solar:calendar-minimalistic-linear",
    href: "/auth/maintenance",
  },

  {
    navlabel: true,
    subheader: "Other",
  },
  {
    id: uniqueId(),
    title: "Menu Level",
    icon: "solar:layers-minimalistic-line-duotone",
    href: "/menulevel/",
    children: [
      {
        id: uniqueId(),
        title: "Level 1",
        icon: "solar:stop-circle-line-duotone",
        href: "/l1",
      },
      {
        id: uniqueId(),
        title: "Level 1.1",
        icon: "solar:stop-circle-line-duotone",
        href: "/l1.1",
        children: [
          {
            id: uniqueId(),
            title: "Level 2",
            icon: "solar:stop-circle-line-duotone",
            href: "/l2",
          },
          {
            id: uniqueId(),
            title: "Level 2.1",
            icon: "solar:stop-circle-line-duotone",
            href: "/l2.1",
            children: [
              {
                id: uniqueId(),
                title: "Level 3",
                icon: "solar:stop-circle-line-duotone",
                href: "/l3",
              },
              {
                id: uniqueId(),
                title: "Level 3.1",
                icon: "solar:stop-circle-line-duotone",
                href: "/l3.1",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Disabled",
    icon: "solar:forbidden-circle-line-duotone",
    href: "/#",
    disabled: true,
  },
  {
    id: uniqueId(),
    title: "SubCaption",
    subtitle: "This is the sutitle",
    icon: "solar:star-line-duotone",
    href: "/#",
  },

  {
    id: uniqueId(),
    title: "Chip",
    icon: "solar:shield-check-line-duotone",
    href: "/#",
    chip: "9",
    chipColor: "primary",
  },
  {
    id: uniqueId(),
    title: "Outlined",
    icon: "solar:smile-circle-outline",
    href: "/#",
    chip: "outline",
    variant: "outlined",
    chipColor: "primary",
  },
  {
    id: uniqueId(),
    title: "External Link",
    external: true,
    icon: "solar:link-square-linear",
    href: "https://google.com",
  },
];

export default Menuitems;
